2018-11-15 12:40:47.3588|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 12:43:21.5934|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 12:59:11.8442|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 13:09:38.0349|ERROR|DataStore.repository.store`1|An error occurred while updating the entries. See the inner exception for details.
2018-11-15 13:09:38.0449|ERROR|DataStore.repository.store`1|   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DataStore.repository.store`1.<Save>d__8.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\repository\store.cs:line 100
2018-11-15 13:09:38.2448|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 13:09:38.2448|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 13:09:38.2448|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 13:09:38.2727|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-15 13:09:38.2747|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.SendMail(ViewModelNonLife mail, Boolean IsCustodian, String template, String imagepath) in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 342
2018-11-15 13:09:38.2747|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 13:09:38.2747|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 13:09:38.2747|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 13:12:37.2284|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 13:13:17.5327|ERROR|DataStore.repository.store`1|An error occurred while updating the entries. See the inner exception for details.
2018-11-15 13:13:18.2134|ERROR|DataStore.repository.store`1|   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DataStore.repository.store`1.<Save>d__8.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\repository\store.cs:line 105
2018-11-15 13:13:18.9020|ERROR|CustodianEveryWhereV2._0.Controllers.ClaimsController|An error occurred while updating the entries. See the inner exception for details.
2018-11-15 13:13:18.9020|ERROR|CustodianEveryWhereV2._0.Controllers.ClaimsController|   at DataStore.repository.store`1.<Save>d__8.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\repository\store.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CustodianEveryWhereV2._0.Controllers.ClaimsController.<ProcessNonLifeClaims>d__7.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\CustodianEveryWhereV2.0\Controllers\ClaimsController.cs:line 302
2018-11-15 13:13:18.9020|ERROR|CustodianEveryWhereV2._0.Controllers.ClaimsController|System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStoreAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesInternalAsync>d__31.MoveNext()
2018-11-15 13:13:42.2121|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 13:33:00.5639|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 13:40:51.8214|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 13:45:28.7301|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 13:53:51.0757|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 14:09:05.7041|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 14:09:43.3508|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 14:09:43.3528|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 14:09:43.3528|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 14:09:43.3837|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-15 14:09:43.4087|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.SendMail(ViewModelNonLife mail, Boolean IsCustodian, String template, String imagepath) in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 342
2018-11-15 14:09:43.4087|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 14:09:43.4087|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 14:09:43.4087|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 14:12:27.4308|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 14:13:08.9467|ERROR|DataStore.repository.store`1|An error occurred while updating the entries. See the inner exception for details.
2018-11-15 14:13:08.9737|ERROR|DataStore.repository.store`1|   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DataStore.repository.store`1.<Save>d__8.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\repository\store.cs:line 105
2018-11-15 14:13:09.0606|ERROR|CustodianEveryWhereV2._0.Controllers.ClaimsController|An error occurred while updating the entries. See the inner exception for details.
2018-11-15 14:13:09.0606|ERROR|CustodianEveryWhereV2._0.Controllers.ClaimsController|   at DataStore.repository.store`1.<Save>d__8.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\repository\store.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CustodianEveryWhereV2._0.Controllers.ClaimsController.<ProcessNonLifeClaims>d__7.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\CustodianEveryWhereV2.0\Controllers\ClaimsController.cs:line 302
2018-11-15 14:13:09.0726|ERROR|CustodianEveryWhereV2._0.Controllers.ClaimsController|System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.<UpdateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStoreAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesInternalAsync>d__31.MoveNext()
2018-11-15 14:13:19.3209|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 14:17:02.6618|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 14:18:33.6770|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 14:18:54.8141|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 14:18:54.8141|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 14:18:54.8251|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 14:18:54.8550|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-15 14:18:54.8730|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.SendMail(ViewModelNonLife mail, Boolean IsCustodian, String template, String imagepath) in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 342
2018-11-15 14:18:54.8730|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 14:18:54.8730|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 14:18:54.8880|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:07:51.8676|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 15:08:15.0553|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:08:15.0603|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:08:15.0603|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:08:15.1103|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-15 15:08:15.1342|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.SendMail(ViewModelNonLife mail, Boolean IsCustodian, String template, String imagepath) in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 342
2018-11-15 15:08:15.1342|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:08:15.1342|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:08:15.1342|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:15:54.8890|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 15:19:53.4536|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 15:22:03.9274|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:22:03.9274|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:22:03.9404|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:22:03.9864|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-15 15:22:04.0124|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.SendMail(ViewModelNonLife mail, Boolean IsCustodian, String template, String imagepath) in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 342
2018-11-15 15:22:04.0124|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:22:04.0124|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:22:04.0124|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:22:27.5860|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 15:23:24.8680|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 15:25:00.7189|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:25:00.7189|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:25:00.7299|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:25:00.8928|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-15 15:25:00.8928|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.SendMail(ViewModelNonLife mail, Boolean IsCustodian, String template, String imagepath) in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 342
2018-11-15 15:25:00.8928|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:25:00.8928|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:25:00.8928|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:27:04.7590|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-15 15:27:11.0778|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:27:11.0778|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:27:11.0928|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:27:11.3176|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-15 15:27:11.3176|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.SendMail(ViewModelNonLife mail, Boolean IsCustodian, String template, String imagepath) in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 342
2018-11-15 15:27:11.3176|INFO|DataStore.Utilities.Utility|About to send email to okjool2012@gmail.com
2018-11-15 15:27:11.3226|INFO|DataStore.Utilities.Utility|About to send temp to here
2018-11-15 15:27:11.3226|INFO|DataStore.Utilities.Utility|About to send param to all
2018-11-15 15:29:42.6514|INFO|CustodianEveryWhereV2._0.Controllers.ClaimsController|about to validate request params for ProcessNonLifeClaims()
2018-11-19 13:36:01.9077|INFO|CustodianEveryWhereV2._0.Controllers.GITController|new request {"vehicle_registration_no":"545SDSF","insured_name":"Itaba Oscar","sum_insured":5000.0,"address":"17 new balogun street fadeyi ","email_address":"oscardybabaphd@gmail.com","phone_number":"08069314541","merchant_id":"CUST_00001","hash":"B07FD8F45661DC4BDC5E9869B7D6571D4C69418B04586608DE1827D73305CE30"}
2018-11-19 13:38:53.1876|INFO|CustodianEveryWhereV2._0.Controllers.GITController|new request {"vehicle_registration_no":"545SDSF","insured_name":"Itaba Oscar","sum_insured":5000.0,"address":"17 new balogun street fadeyi ","email_address":"oscardybabaphd@gmail.com","phone_number":"08069314541","merchant_id":"CUST_00001","hash":"B07FD8F45661DC4BDC5E9869B7D6571D4C69418B04586608DE1827D73305CE30"}
2018-11-19 13:40:52.2076|ERROR|DataStore.Utilities.Utility|Object reference not set to an instance of an object.
2018-11-19 13:40:52.2076|ERROR|DataStore.Utilities.Utility|   at DataStore.Utilities.Utility.<SendGITMail>d__15.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 537
2019-01-23 17:12:35.5419|ERROR|DataStore.Utilities.Utility|The type initializer for 'Oracle.DataAccess.Client.OracleConnection' threw an exception.
2019-01-23 17:12:35.7101|ERROR|DataStore.Utilities.Utility|   at Oracle.DataAccess.Client.OracleConnection..ctor(String connectionString)
   at DataStore.Utilities.Utility.<GetLifeClaimsDetails>d__19.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 713
2019-01-23 17:12:35.7101|ERROR|DataStore.Utilities.Utility|Oracle.DataAccess.Client.OracleException The provider is not compatible with the version of Oracle client    at Oracle.DataAccess.Client.OracleInit.Initialize()
   at Oracle.DataAccess.Client.OracleConnection..cctor()
2019-01-23 17:12:40.9082|ERROR|DataStore.Utilities.Utility|The type initializer for 'Oracle.DataAccess.Client.OracleConnection' threw an exception.
2019-01-23 17:12:40.9111|ERROR|DataStore.Utilities.Utility|   at Oracle.DataAccess.Client.OracleConnection..ctor(String connectionString)
   at DataStore.Utilities.Utility.<GetLifeClaimsDetails>d__19.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 713
2019-01-23 17:12:40.9111|ERROR|DataStore.Utilities.Utility|Oracle.DataAccess.Client.OracleException The provider is not compatible with the version of Oracle client    at Oracle.DataAccess.Client.OracleInit.Initialize()
   at Oracle.DataAccess.Client.OracleConnection..cctor()
2019-01-23 17:33:07.5674|ERROR|DataStore.Utilities.Utility|The type initializer for 'Oracle.DataAccess.Client.OracleConnection' threw an exception.
2019-01-23 17:33:08.2551|ERROR|DataStore.Utilities.Utility|   at Oracle.DataAccess.Client.OracleConnection..ctor(String connectionString)
   at DataStore.Utilities.Utility.<GetLifeClaimsDetails>d__19.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 713
2019-01-23 17:33:09.2145|ERROR|DataStore.Utilities.Utility|Oracle.DataAccess.Client.OracleException The provider is not compatible with the version of Oracle client    at Oracle.DataAccess.Client.OracleInit.Initialize()
   at Oracle.DataAccess.Client.OracleConnection..cctor()
2019-01-23 17:35:02.3492|ERROR|DataStore.Utilities.Utility|The type initializer for 'Oracle.DataAccess.Client.OracleConnection' threw an exception.
2019-01-23 17:35:02.3492|ERROR|DataStore.Utilities.Utility|   at Oracle.DataAccess.Client.OracleConnection..ctor(String connectionString)
   at DataStore.Utilities.Utility.<GetLifeClaimsDetails>d__19.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 713
2019-01-23 17:35:02.3621|ERROR|DataStore.Utilities.Utility|Oracle.DataAccess.Client.OracleException The provider is not compatible with the version of Oracle client    at Oracle.DataAccess.Client.OracleInit.Initialize()
   at Oracle.DataAccess.Client.OracleConnection..cctor()
2019-01-23 17:35:22.7538|ERROR|DataStore.Utilities.Utility|The type initializer for 'Oracle.DataAccess.Client.OracleConnection' threw an exception.
2019-01-23 17:35:22.7538|ERROR|DataStore.Utilities.Utility|   at Oracle.DataAccess.Client.OracleConnection..ctor(String connectionString)
   at DataStore.Utilities.Utility.<GetLifeClaimsDetails>d__19.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\DataStore\Utilities\Utility.cs:line 713
2019-01-23 17:35:22.7538|ERROR|DataStore.Utilities.Utility|Oracle.DataAccess.Client.OracleException The provider is not compatible with the version of Oracle client    at Oracle.DataAccess.Client.OracleInit.Initialize()
   at Oracle.DataAccess.Client.OracleConnection..cctor()
2019-02-12 14:39:02.5132|INFO|CustodianEveryWhereV2._0.Controllers.AgentController|Authorization denied for policy search HO/V/29/B0001235
2019-02-12 14:41:49.4137|ERROR|CustodianEveryWhereV2._0.Controllers.AgentController|Server was unable to process request. ---> The parameterized query '(@merchantID nvarchar(4000),@mPassword nvarchar(4000))SELECT * f' expects the parameter '@merchantID', which was not supplied.
2019-02-12 14:41:49.5696|ERROR|CustodianEveryWhereV2._0.Controllers.AgentController|   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass7_0`1.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CustodianEveryWhereV2._0.Controllers.AgentController.<GetPolicyDetails>d__4.MoveNext() in C:\Users\OItaba\Documents\Visual Studio 2015\Projects\CustodianEveryWhereV2.0\CustodianEveryWhereV2.0\Controllers\AgentController.cs:line 82
2019-02-12 14:41:49.5766|ERROR|CustodianEveryWhereV2._0.Controllers.AgentController|
2019-02-12 14:45:52.5967|INFO|CustodianEveryWhereV2._0.Controllers.AgentController|raw api response  {"PolicyNo":"HO/V/29/B0001235         ","PolicyEBusiness":"NULL","AgenctNum":"B1002/HO  ","AgenctName":"STANBIC IBTC INSURANCE BROKERS LIMITED                                                              ","InsuredNum":"00027754  ","InsuredName":"IYOHA                                                                           ","InsuredOthName":"OLAJUMOKE (MRS.)                                  ","InsAddr1":"C/O STANBIC IBTC INSURANCE                        ","InsAddr2":"WEALTHHOUSE, PLOT 1678 OLAKUNL                    ","InsAddr3":"                                                  ","TelNum":"08033340710                                       ","InsuredTelNum":"08033340710                                       ","InsuredEmail":"insurancesolution@stanbicibtc.com                                                         ","DOB":"0001-01-01T00:00:00","InsState":"Lagos State                                       ","InsLGA":"Eti-Osa                                           ","BizUnit":"PRIVATE CAR INSURANCE                                       ","InsOccup":"BANKING                                           ","BizBranch":"HO  ","Startdate":"2017-04-07T00:00:00","Enddate":"2018-04-06T00:00:00","SumIns":2000000.00,"mPremium":40000.00,"OutPremium":40000.00,"InstPremium":40000.00}
2020-05-15 16:47:04.6256|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:47:04.6746|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 16:47:04.6746|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:48:22.4177|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|An error occurred while executing the command definition. See the inner exception for details.
2020-05-15 16:48:23.3521|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.Execute(MergeOption mergeOption)
   at System.Data.Entity.Core.Objects.DataClasses.EntityReference`1.Load(MergeOption mergeOption)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.DeferredLoad()
   at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.LoadProperty[TItem](TItem propertyValue, String relationshipName, String targetRoleName, Boolean mustBeNull, Object wrapperObject)
   at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.<>c__DisplayClass7`2.<GetInterceptorDelegate>b__2(TProxy proxy, TItem item)
   at System.Data.Entity.DynamicProxies.SelectedMealPlan_82A26D11E512CBF377F01A45AE9971AA8BD9ACC0E716736A78DD9F5734F103C5.get_MealPlan()
   at CustodianEveryWhereV2._0.Controllers.MealPlanController.<>c.<GetMyMealPlan>b__7_3(SelectedMealPlan x) in C:\Users\USER\Documents\CustodianProject\custodianeverywhere2.0new\CustodianEveryWhereV2.0\Controllers\MealPlanController.cs:line 210
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at CustodianEveryWhereV2._0.Controllers.MealPlanController.<GetMyMealPlan>d__7.MoveNext() in C:\Users\USER\Documents\CustodianProject\custodianeverywhere2.0new\CustodianEveryWhereV2.0\Controllers\MealPlanController.cs:line 211
2020-05-15 16:48:27.3139|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|System.InvalidOperationException: ExecuteReader requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
2020-05-15 16:49:02.2749|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:49:02.3019|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 16:49:02.3019|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:49:31.5272|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|An error occurred while executing the command definition. See the inner exception for details.
2020-05-15 16:49:35.2821|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.Execute(MergeOption mergeOption)
   at System.Data.Entity.Core.Objects.DataClasses.EntityReference`1.Load(MergeOption mergeOption)
   at System.Data.Entity.Core.Objects.DataClasses.RelatedEnd.DeferredLoad()
   at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.LoadProperty[TItem](TItem propertyValue, String relationshipName, String targetRoleName, Boolean mustBeNull, Object wrapperObject)
   at System.Data.Entity.Core.Objects.Internal.LazyLoadBehavior.<>c__DisplayClass7`2.<GetInterceptorDelegate>b__2(TProxy proxy, TItem item)
   at System.Data.Entity.DynamicProxies.SelectedMealPlan_82A26D11E512CBF377F01A45AE9971AA8BD9ACC0E716736A78DD9F5734F103C5.get_MealPlan()
   at CustodianEveryWhereV2._0.Controllers.MealPlanController.<>c.<GetMyMealPlan>b__7_3(SelectedMealPlan x) in C:\Users\USER\Documents\CustodianProject\custodianeverywhere2.0new\CustodianEveryWhereV2.0\Controllers\MealPlanController.cs:line 210
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at CustodianEveryWhereV2._0.Controllers.MealPlanController.<GetMyMealPlan>d__7.MoveNext() in C:\Users\USER\Documents\CustodianProject\custodianeverywhere2.0new\CustodianEveryWhereV2.0\Controllers\MealPlanController.cs:line 211
2020-05-15 16:49:35.2821|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|System.InvalidOperationException: ExecuteReader requires an open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<Reader>b__c(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
2020-05-15 16:49:50.0000|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:49:50.0000|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 16:49:50.0000|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:56:58.7774|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:56:58.8084|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 16:56:58.8114|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:57:37.2495|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 16:57:37.2495|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 16:57:37.2495|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:04:35.3427|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:04:35.3857|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 17:04:35.3857|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:11:47.0761|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:11:47.1181|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 17:11:47.1181|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:16:50.6445|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|An item with the same key has already been added.
2020-05-15 17:16:50.6655|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at CustodianEveryWhereV2._0.Controllers.MealPlanController.<GetMyMealPlan>d__7.MoveNext() in C:\Users\USER\Documents\CustodianProject\custodianeverywhere2.0new\CustodianEveryWhereV2.0\Controllers\MealPlanController.cs:line 229
2020-05-15 17:16:50.6655|ERROR|CustodianEveryWhereV2._0.Controllers.MealPlanController|
2020-05-15 17:16:51.0542|ERROR|DataStore.repository.store`1|The underlying provider failed on Open.
2020-05-15 17:16:51.0692|ERROR|DataStore.repository.store`1|   at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at DataStore.repository.store`1.<>c__DisplayClass6_0.<FindOneByCriteria>b__0() in C:\Users\USER\Documents\CustodianProject\custodianeverywhere2.0new\DataStore\repository\store.cs:line 64
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DataStore.repository.store`1.<FindOneByCriteria>d__6.MoveNext() in C:\Users\USER\Documents\CustodianProject\custodianeverywhere2.0new\DataStore\repository\store.cs:line 62
2020-05-15 17:17:37.7452|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:17:37.7572|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 17:17:37.7572|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:27:22.6778|INFO|DataStore.Utilities.Utility|Passed hash F37C94F20665755B8264AB6845C10882
2020-05-15 17:27:22.7198|INFO|DataStore.Utilities.Utility|my hash partten oscardybabaphd@gmail.comTest_vkMqq$%ww
2020-05-15 17:27:22.7198|INFO|DataStore.Utilities.Utility|Computed hash F37C94F20665755B8264AB6845C10882
